apiVersion: v1 # Service 는 core v1 API 를 사용
kind: Service

metadata:
  name: sleep-2 # Service name 은 domain name 으로 사용

# Service spec 에는 selecor 와 port 의 목록이 포함되어야 한다
spec:
  selector:
    app: sleep-2 # app label 값이 sleep-2 인 모든 pod 가 대상
  ports:
    - port: 80 # 80번 port listen -> 80번 port 로 트래픽 전달