apiVersion: v1
kind: Service

metadata:
  name: numbers-web-node

spec:
  ports:
    - port: 8080        # 다른 파드가 서비스에 접근하기 위해 사용하는 포트
      targetPort: 80    # 대상 파드에 트래픽을 전달하는 포트
      nodePort: 30080   # 서비스가 외부에 공개되는 포트 
  selector:
    app: numbers-web
  type: NodePort      